### ISSUE TITLE
Занятие 2.

### ISSUE THREAD

**Issue by stsdmchv** [sashuutakap837/Sashutakap837#3]
Задачи 4-9 должны быть решены с использованием возможностей функций.

**Comment by sashuutakap837** [comment]
Их нужно переделать ?

Ср, 29 сент. 2021 г. в 13:06, Stanislav Demichev ***@***.***>:

**Comment by stsdmchv** [comment]
> Их нужно переделать ? Ср, 29 сент. 2021 г. в 13:06, Stanislav Demichev ***@***.***>:

Да
